"""fix organization member response nullable fields

Revision ID: 55ea64c4127b
Revises: 35e28ce04d69
Create Date: 2026-09-04 17:20:12.874911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ea64c4127b'
down_revision: Union[str, None] = '35e28ce04d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_owner_id'), 'chat_sessions', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_owner_id'), table_name='chat_sessions')
    # ### end Alembic commands ###
