"""Adding Process_status and changing content nullable to True

Revision ID: 5c1808190ff8
Revises: 5e95bce38237
Create Date: 2026-08-13 23:57:47.264785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1808190ff8'
down_revision: Union[str, None] = '5e95bce38237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=True))
    op.alter_column('documents', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
