"""add columns to users and organization_members

Revision ID: aef1307a8ae0
Revises: b7f2c9a41d03
Create Date: 2026-08-31 20:55:09.038417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef1307a8ae0'
down_revision: Union[str, None] = 'b7f2c9a41d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('description', sa.String(), nullable=True))
    op.add_column('organization_members', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('organization_members', 'status')
    op.drop_column('organization_members', 'description')
    # ### end Alembic commands ###
